require.include ( "classes/sprites/sprite_effects/FloatSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/BubbleSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/DirtSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/TopDirtSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/LightBeamSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/SinkingSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/FlickerSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/SwapSpriteEffect" );
require.include ( "classes/sprites/sprite_effects/SpriteFadeEffect" );
